repository:
  name: preview-tester
  description: repository for testing preview instances
  visibility: public
  has_wiki: false
  has_discussions: false
  homepage: https://github.com/repository-settings/hosted-instance
